name: Reusable Terraform Apply (Prod)

on:
  workflow_call:
    inputs:
      tf_dir:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Production Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - uses: ./.github/actions/terraform-init
        with:
          tf_dir: ${{ inputs.tf_dir }}

      - name: Terraform Plan (Prod)
        shell: bash
        run: |
          cd ${{ inputs.tf_dir }}
          terraform plan -out=tfplan -no-color

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.tf_dir }}/tfplan

  apply:
    name: Production Apply
    runs-on: ubuntu-latest
    needs: plan
    environment: dev # ðŸ”’ MANUAL APPROVAL HERE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.tf_dir }}

      - uses: ./.github/actions/terraform-init
        with:
          tf_dir: ${{ inputs.tf_dir }}

      - name: Terraform Apply
        shell: bash
        run: |
          cd ${{ inputs.tf_dir }}
          terraform apply -auto-approve tfplan
